apiVersion: v1
kind: Namespace
metadata:
  name: production

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp-production
  namespace: production
spec:
  replicas: 3
  selector:
    matchLabels:
      app: myapp
      environment: production
  template:
    metadata:
      labels:
        app: myapp
        environment: production
    spec:
      containers:
      - name: myapp
        image: hbjprojectdevops/st2dce:VERSION_PLACEHOLDER
        ports:
        - containerPort: 8080

---

apiVersion: v1
kind: Service
metadata:
  name: myapp-production
  namespace: production
spec:
  selector:
    app: myapp
    environment: production
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
