apiVersion: apps/v1
kind: Deployment
metadata:
  name: st2dce-development
spec:
  replicas: 2
  selector:
    matchLabels:
      app: st2dce
      env: development
  template:
    metadata:
      labels:
        app: st2dce
        env: development
    spec:
      containers:
        - name: st2dce
          image: hbjprojectdevops/st2dce:latest
          ports:
            - containerPort: 8080
