apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp-development
spec:
  replicas: 2
  selector:
    matchLabels:
      app: myapp
      environment: development
  template:
    metadata:
      labels:
        app: myapp
        environment: development
    spec:
      containers:
      - name: myapp
        image: hbjprojectdevops/st2dce:${VERSION_PLACEHOLDER}
        ports:
        - containerPort: 8080

---
apiVersion: v1
kind: Service
metadata:
  name: myapp-development
spec:
  selector:
    app: myapp
    environment: development
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080

