apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp-production
spec:
  replicas: 3
  selector:
    matchLabels:
      app: myapp
      environment: production
  template:
    metadata:
      labels:
        app: myapp
        environment: production
    spec:
      containers:
      - name: myapp
        image: hbjprojectdevops/st2dce:latest
        ports:
        - containerPort: 8080

---
apiVersion: v1
kind: Service
metadata:
  name: myapp-production
spec:
  selector:
    app: myapp
    environment: production
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080

